// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2uTCvkjuUr92Ln3T9gnk8i4Sea2qkVkE',
    appId: '1:68953874450:web:260738f494351df23ff8cb',
    messagingSenderId: '68953874450',
    projectId: 'memessengzroute',
    authDomain: 'memessengzroute.firebaseapp.com',
    storageBucket: 'memessengzroute.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChS4QLZQZQPBTl5Bk27Xx7bDOYRmCwZis',
    appId: '1:68953874450:android:b524543955e4a8ac3ff8cb',
    messagingSenderId: '68953874450',
    projectId: 'memessengzroute',
    storageBucket: 'memessengzroute.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo-mX5UqHKq56U2UnbgfSA0JzYJ8x_S7Q',
    appId: '1:68953874450:ios:d6522400bd24c35e3ff8cb',
    messagingSenderId: '68953874450',
    projectId: 'memessengzroute',
    storageBucket: 'memessengzroute.firebasestorage.app',
    iosBundleId: 'com.messengzroute.myChatZroute',
  );
}
